# Copyright 2007-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0


from gems_views_builder.aggregators.scenario_aggregator import ScenarioAggregator, make_scenario_operator
from gems_views_builder.aggregators.time_aggregator import perform_time_aggregations
from gems_views_builder.input.view_config import AggregationPattern, TimeGranularity, ViewConfig
from gems_views_builder.input.catalog import Metric
from gems_views_builder.aggregators.time_aggregator import TimeAggregator
from gems_views_builder.metric_view import MetricView, TemporalMetricView
from gems_views_builder.spatial_filter import SpatialFilter

# This class is a Decorator for TimeAggregator
# The intention of this class is to record a MetricView generated by a TimeAggregator
# in a dictionary, for any further possible use.
class TimeAggregatorDecorator: # Should inherit from base common class
    def __init__(self, time_aggregated_metric_views: dict[TimeGranularity, MetricView],
                 time_granularity: TimeGranularity) -> None:
        self.time_aggregated_metric_views = time_aggregated_metric_views
        self.time_granularity = time_granularity
        self.time_aggregator = TimeAggregator(time_granularity)

    def run(self, metric_view: TemporalMetricView, metric: Metric) -> MetricView:
        if self.time_granularity not in self.time_aggregated_metric_views:
            return self.time_aggregator.run(metric_view, metric)
        return self.time_aggregated_metric_views[self.time_granularity]

class PatternAggregator:
    def __init__(self, pattern: AggregationPattern,
                 time_aggregated_metric_views: dict[TimeGranularity, MetricView])-> None:
        self.time_aggregator = TimeAggregatorDecorator(time_aggregated_metric_views, pattern.time_granularity)
        self.scenario_aggregator = ScenarioAggregator(make_scenario_operator(pattern.scenario),
                                                      SpatialFilter(pattern.spatial_filter))

    def run(self, metric_view: TemporalMetricView, metric: Metric) -> MetricView:
        temporal_metric_view = self.time_aggregator.run(metric_view, metric)
        return self.scenario_aggregator.run(temporal_metric_view)


class AggregationPatternList:
    def __init__(self, view_config: ViewConfig) -> None:
        self.aggregation_patterns: list[PatternAggregator] = []
        self.time_aggregated_metric_views: dict[TimeGranularity, MetricView] = {}

        for pattern in view_config.aggregation_patterns:
            self.aggregation_patterns.append(PatternAggregator(pattern, self.time_aggregated_metric_views))

    def run(self, metric_view: TemporalMetricView, metric: Metric) -> list[MetricView]:
        metric_views: list[MetricView] = []
        for pattern in self.aggregation_patterns:
            metric_view = pattern.run(metric_view, metric)
            metric_views.append(metric_view)
        return metric_views