# Copyright 2007-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0

from gems_views_builder.aggregators.scenario_aggregator import ScenarioAggregator
from gems_views_builder.aggregators.time_aggregator import TimeAggregatorDecorator
from gems_views_builder.input.catalog import Metric
from gems_views_builder.input.view_config import AggregationPattern, ViewConfig
from gems_views_builder.metric_view import MetricView, TemporalMetricView


class PatternAggregator:
    def __init__(self, pattern: AggregationPattern) -> None:
        self.time_aggregator = TimeAggregatorDecorator(pattern.time_granularity)
        self.scenario_aggregator = ScenarioAggregator(pattern)

    def run(self, metric_view: MetricView, metric: Metric) -> MetricView:
        temporal_metric_view = self.time_aggregator.run(metric_view, metric)
        return self.scenario_aggregator.run(temporal_metric_view)


class AggregationPatternList:
    def __init__(self, view_config: ViewConfig) -> None:
        self.aggregation_patterns: list[PatternAggregator] = []
        for pattern in view_config.aggregation_patterns:
            self.aggregation_patterns.append(PatternAggregator(pattern))

    def run(self, metric_view: MetricView, metric: Metric) -> list[TemporalMetricView]:
        # For each new metric, clearing the storage of views generated by time aggregations
        TimeAggregatorDecorator.views_storage.clear()

        views: list[MetricView] = []
        for pattern in self.aggregation_patterns:
            view = pattern.run(metric_view, metric)
            views.append(view)
        return views
