# Copyright 2007-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0

import atexit
import logging
import tempfile
import uuid
from pathlib import Path
from shutil import rmtree

import polars as pl

from gems_views_builder.common import PARQUET_COMPRESSION, PARQUET_COMPRESSION_LEVEL, PARQUET_ROW_GROUP_SIZE
from gems_views_builder.input.catalog import AggregOperatorType, Metric
from gems_views_builder.input.view_config import TimeGranularity
from gems_views_builder.metric_view import MetricView, TemporalMetricView

# # Polars truncate windows are strings like "1h", "1d", "1w", "1mo", "1y".
TRUNCATE_WINDOWS: dict[TimeGranularity, str] = {
    TimeGranularity.HOUR: "1h",
    TimeGranularity.DAY: "1d",
    TimeGranularity.WEEK: "1w",
    TimeGranularity.MONTH: "1mo",
    TimeGranularity.YEAR: "1y",
}


class TimeAggregator:
    def __init__(self, time_granularity: TimeGranularity) -> None:
        self._time_granularity = time_granularity
        self._root_dir = Path(tempfile.mkdtemp())
        self._temporal_aggregation_dir = self._root_dir / "views" / "temporal_aggregation"
        self._temporal_aggregation_dir.mkdir(parents=True, exist_ok=True)
        # # The temporal aggregation files are the pipeline's final output: they must
        # # outlive this aggregator because accumulate_on_disk() reads them after build() returns and
        # # the ViewBuilder (and this aggregator) has already been garbage collected.
        # # Cleaning up in __del__ would delete them too early, so we defer removal of
        # # the whole temp tree until interpreter exit instead.
        atexit.register(rmtree, self._root_dir, True)

    def run(self, metric_view: TemporalMetricView, metric: Metric) -> MetricView:
        """
        Step 2.C from POC[temporal aggregation]: Group by metric_id, metric_location, breakdown_properties, absolute_time_index, scenario
        """
        logging.info(f"[{metric.id}] Aggregating temporally with operator {metric.time_operator.value}")
        lazy_metric_view = pl.scan_parquet(metric_view.persistence_path)

        aggreg_op = aggregate_into_column(metric.time_operator, "granular_metric_value")
        date_column = date_column_into_time_granularity(self._time_granularity)

        view = (
            lazy_metric_view.with_columns(date_column)
            .group_by(
                [
                    "metric_id",
                    "metric_location",
                    "breakdown_properties",
                    "scenario_id",
                    "view_date",
                ]
            )
            .agg(aggreg_op)
            .select(
                [
                    "metric_id",
                    "metric_location",
                    "breakdown_properties",
                    "view_date",
                    "scenario_id",
                    pl.col("metric_value").cast(pl.Float64),
                ]
            )
        )
        # # Safest and most elegant option to remove part counter
        # # https://www.researchgate.net/publication/215758035_A_Universally_Unique_IDentifier_UUID_URN_Namespace
        file_path = (
            self._temporal_aggregation_dir / f"{self._time_granularity.value}_{metric.id}_{uuid.uuid4()}.parquet"
        )
        view.sink_parquet(
            path=file_path,
            compression=PARQUET_COMPRESSION,
            compression_level=PARQUET_COMPRESSION_LEVEL,
            row_group_size=PARQUET_ROW_GROUP_SIZE,
        )
        logg_write(metric, file_path)
        return MetricView(file_path, self._time_granularity)


# This class is a Decorator (for TimeAggregator) : it adds functionality to TimeAggregator without
# touching it : it records a MetricView generated by the TimeAggregator
# in a dictionary (given at construction of a TimeAggregator), for any further possible reuse.
class TimeAggregatorDecorator:  # Should inherit from base common class
    views_storage: dict[TimeGranularity, MetricView] = {}

    def __init__(self, time_granularity: TimeGranularity) -> None:
        self.time_granularity = time_granularity
        self.time_aggregator = TimeAggregator(time_granularity)

    def run(self, metric_view: TemporalMetricView, metric: Metric) -> MetricView:
        if self.time_granularity not in self.views_storage:
            view = self.time_aggregator.run(metric_view, metric)
            self.views_storage[self.time_granularity] = view # Registering the view
            return view
        return self.views_storage[self.time_granularity]


def logg_write(metric: Metric, file_path: Path) -> None:
    logging.info(f"[{metric.id}] Temporal aggregation written to {file_path}")


def date_column_into_time_granularity(time_granularity: TimeGranularity) -> pl.Expr:
    return pl.col("granular_date").dt.truncate(TRUNCATE_WINDOWS[time_granularity]).alias("view_date")


def aggregate_into_column(agg_operator: AggregOperatorType, column_name: str) -> pl.Expr:
    return (pl.col(column_name).sum() if agg_operator == AggregOperatorType.SUM else pl.col(column_name).mean()).alias(
        "metric_value"
    )
